### ISSUE TITLE
Building on Modern Linux

### ISSUE THREAD

**Issue by clort81** [llbit/gravazoid#1]
```
/pr/games/gravazoid$ make
make -C cttf libcttf.a vex
make[1]: Entering directory '/media/sd/pcbak2/Projects/games/gravazoid/cttf'
make[1]: *** No rule to make target 'libcttf.a'.  Stop.
make[1]: Leaving directory '/media/sd/pcbak2/Projects/games/gravazoid/cttf'
make: *** [Makefile:21: cttf] Error 2
```
What's this?
I'll poke around and update changes to my fork.

**Comment by clort81** [comment]
Ah it was not pulling in the cttf from the git clone (hangs upon --recursive) so I cloned cttf manually.
```
$ make
make -C cttf libcttf.a vex
make[1]: Entering directory '/media/sd/Projects/Games/gravazoid0/cttf'
make[1]: 'libcttf.a' is up to date.
make[1]: 'vex' is up to date.
make[1]: Leaving directory '/media/sd/Projects/Games/gravazoid0/cttf'
gcc -o lvledit lvledit.o render.o sfx.o block.o memfile.o -Lcttf -lcttf -lSDL -lGLU -lGL -g
/usr/bin/ld: cttf/libcttf.a(triangulate.o): undefined reference to symbol 'sqrt@@GLIBC_2.17'
/usr/bin/ld: /lib/aarch64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:27: lvledit] Error 1
```
that gcc invocation needs -lm added to work
So manually linking game and lvledit with -lm i get executeables, but ttf.c is broken...
```
(gdb) run
Starting program: /media/sd/Projects/Games/gravazoid0/game 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0xfffff664f060 (LWP 279038)]
[New Thread 0xfffff1a0e060 (LWP 279039)]
[Thread 0xfffff1a0e060 (LWP 279039) exited]

Thread 1 "game" received signal SIGSEGV, Segmentation fault.
0x0000fffff7ba989c in __GI__IO_fread (buf=0xfffffffff0d8, size=12, count=1, fp=0xffffffffaab39760) at ./libio/iofread.c:37
37      ./libio/iofread.c: No such file or directory.
(gdb) bt
#0  0x0000fffff7ba989c in __GI__IO_fread (buf=0xfffffffff0d8, size=12, count=1, fp=0xffffffffaab39760) at ./libio/iofread.c:37
#1  0x0000aaaaaaab26cc in ttf_load (file=0xffffffffaab39760) at ttf.c:772
#2  0x0000aaaaaaaaef50 in load_font_file (fp=0xffffffffaab39760, ipl=3) at text.c:80
#3  0x0000aaaaaaaa5ff0 in load_resources () at main.c:882
#4  0x0000aaaaaaaa6158 in main (argc=1, argv=0xfffffffff338) at main.c:910
(gdb)
```
hmm ./pusselbit.h and Pusselbit.ttf are in current directory...
